name: openapi_code_builder
description: Generate Dtos, client and server scaffolds for openapi specs.
version: 1.1.4+4
homepage: https://github.com/hpoul/openapi_dart/tree/master/packages/openapi_code_builder

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  logging: ^1.0.1
  logging_appenders: ^1.1.0
  meta: ^1.5.0
  openapi_base: ^1.1.0
  path: ^1.8.0
  dart_style: ^2.0.1
  code_builder: ^4.0.0
  build: ^2.0.2
  source_gen: ^1.0.2
  open_api_forked: ^3.0.0+6
  yaml: ^3.1.0
  json_annotation: ^4.0.1
  recase: ^4.1.0
  quiver: ^3.0.1
  built_collection: ^5.1.0
  collection: ^1.15.0

dev_dependencies:
  lints: ^3.0.0
