name: openapi_base
description: Open API base implementation for client/server to be used with openapi_code_builder.
version: 1.1.0+3
homepage: https://github.com/hpoul/openapi_dart/tree/master/packages/openapi_base

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  #  path: ^1.7.0
  collection: ">=1.16.0 <2.0.0"
  meta: ">=1.3.0 <2.0.0"
  open_api_forked: ">=3.0.0 <4.0.0"
  uri: ^1.0.0
  logging: ">=1.0.0 <2.0.0"
  logging_appenders: ">=1.0.0 <2.0.0"

  uuid: ">=3.0.1 <4.0.0"
  json_annotation: ">=4.0.0 <6.0.0"
  chunked_stream: ">=1.4.1 <2.0.0"

  # server
  shelf: ">=1.0.0 <2.0.0"
  #  shelf_cookie: ">=1.1.1 <2.0.0"

  # for the client:
  http: ">=0.13.0 <2.0.0"

dev_dependencies:
  lints: ^2.0.0
